name: gilot github actions
on:
  push:
    branches:
      - master

jobs:
  gilot-hotspot:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install gilot
    - run: mkdir -p /tmp/artifacts/gilot-report
    - run: gilot log ./ --branch ${{ github.ref }} --full -o /tmp/artifacts/gilot-report/gilot-log.txt
    - run: gilot hotspot  -i /tmp/artifacts/gilot-report/gilot-log.txt | tee -a /tmp/artifacts/gilot-report/hotspot.txt
    - run: gilot plot     -i /tmp/artifacts/gilot-report/gilot-log.txt -o /tmp/artifacts/gilot-report/gilot-plot.png
    - run: gilot hotgraph -i /tmp/artifacts/gilot-report/gilot-log.txt -o /tmp/artifacts/gilot-report/gilot-hotgraph.png
    - run: gilot author   -i /tmp/artifacts/gilot-report/gilot-log.txt -o /tmp/artifacts/gilot-report/gilot-author.png
    - name: Upload gilot report
      uses: actions/upload-artifact@v1
      with:
        name: gilot-repot
        path: /tmp/artifacts/gilot-report
