name: gilot github actions
on:
  push:
    branches:
      - master

jobs:
  gilot-hotspot:
    runs-on: ubuntu-latest
    env:
      ARTIFACT_DIR: /tmp/artifact/gilot-report
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install gilot
    - run: mkdir -p $ARTIFACT_DIR
    - run: gilot log ./ --branch ${{ github.ref }} --full -o $ARTIFACT_DIR/gilot-log.txt
    - run: gilot hotspot  -i $ARTIFACT_DIR/gilot-log.txt | tee -a $ARTIFACT_DIR/hotspot.txt
    - run: gilot plot     -i $ARTIFACT_DIR/gilot-log.txt -o $ARTIFACT_DIR/gilot-plot.png
    - run: gilot hotgraph -i $ARTIFACT_DIR/gilot-log.txt -o $ARTIFACT_DIR/gilot-hotgraph.png
    - run: gilot author   -i $ARTIFACT_DIR/gilot-log.txt -o $ARTIFACT_DIR/gilot-author.png
    - name: Upload gilot report
      uses: actions/upload-artifact@v1
      with:
        name: gilot-repot
        path: ${{ env.ARTIFACT_DIR }}
